### ISSUE TITLE
hangs load for KSP 1.12.x

### ISSUE THREAD

**Issue by zer0Kerbal** [zer0Kerbal/Kaboom#6]
compiled for 1.12.x (no errors or warnings) and it hangs the load at 'loading part upgrades'

**Comment by zer0Kerbal** [comment]
@flart any suggestions?

**Comment by Tacombel** [comment]
Check if you have any copy of miniAVC.dll in your gamedata directory and delete it. It could be that it is also necessary to install zerominiAVC, although this is not clear.

**Comment by zer0Kerbal** [comment]
@Tacombel Thank you -

tried - removed everything except Squad (no DLC's) and MM and Kaboom... same.
Going to try recompiling with .NET 3.5 and then 4.7.2 and see if that is the issue. Don't believe it is.

**Comment by zer0Kerbal** [comment]
well golly gee-whiz... compiling with .NET 4.7.2 seems to have resolved the issue.... was using .4.8

**Comment by Tacombel** [comment]
I think this can explain what is happening with the latest .NET version
https://forum.kerbalspaceprogram.com/index.php?/topic/203262-stuck-on-loading-part-upgrades-112/&do=findComment&comment=4003108

**Comment by zer0Kerbal** [comment]
> I think this can explain what is happening with the latest .NET version
> https://forum.kerbalspaceprogram.com/index.php?/topic/203262-stuck-on-loading-part-upgrades-112/&do=findComment&comment=4003108
thank you @Tacombel 

interesting. however in this specific case it was that .net 4.8 isn't supported in KSP; been having a [fileversion] in everything since 2019 in all the projects.
